# -*- coding: utf-8 -*-
"""Refactorizar_Tarea

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/PaulCalderon98/13ebcd8f3fb672b39437cae4a244f12d/copia-de-refactorizar.ipynb
"""

class persona(): # clase persona
    def __init__(self,nombre,edad): # se inicializa con nombre y edad
        self.nombre=nombre
        self.edad=edad

maikel=persona("Paul Calderón", 30)

# refactorice el siguente codigo 
# medinate expresiones aumentadas https://zephyrnet.com/es/10-formas-de-refactorizar-su-c%C3%B3digo-Python/
count=0
c1=0
for i in  range(20):
  count+=c1
print(count)